/*
 * Copyright (c) 2012 Alvin R. de Leon. All Rights Reserved.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.piraso.ui.base;

import java.net.URL;
import org.apache.commons.lang.StringUtils;
import org.openide.ErrorManager;
import org.piraso.ui.api.HttpSettingsUpdateModel;
import org.piraso.ui.api.extension.AbstractDialog;
import org.piraso.ui.api.manager.SingleModelManagers;
import org.piraso.ui.api.util.NotificationUtils;
import org.piraso.ui.base.manager.HttpUpdateManager;

/**
 *
 * @author adeleon
 */
public class HttpSettingsUpdateDialog extends AbstractDialog {

    private HttpSettingsUpdateModel model;

    /**
     * Creates new form HttpSettingsUpdateDialog
     */
    public HttpSettingsUpdateDialog() {
        super();
        setTitle("Http Settings Update");
        initComponents();
        
        getRootPane().setDefaultButton(btnUpdate);
        setLocationRelativeTo(getOwner());

        model = SingleModelManagers.HTTP_SETTINGS.get();
        if(model.getUrl() != null) {
            txtURL.setText(model.getUrl().toString());
        }

        chkSyncOnStartup.setSelected(model.isLoadOnStartup());
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtURL = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        chkSyncOnStartup = new javax.swing.JCheckBox();
        btnAuthenticate = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText(org.openide.util.NbBundle.getMessage(HttpSettingsUpdateDialog.class, "HttpSettingsUpdateDialog.jLabel1.text")); // NOI18N

        txtURL.setText(org.openide.util.NbBundle.getMessage(HttpSettingsUpdateDialog.class, "HttpSettingsUpdateDialog.txtURL.text")); // NOI18N

        btnUpdate.setText(org.openide.util.NbBundle.getMessage(HttpSettingsUpdateDialog.class, "HttpSettingsUpdateDialog.btnUpdate.text")); // NOI18N
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnCancel.setText(org.openide.util.NbBundle.getMessage(HttpSettingsUpdateDialog.class, "HttpSettingsUpdateDialog.btnCancel.text")); // NOI18N
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        chkSyncOnStartup.setText(org.openide.util.NbBundle.getMessage(HttpSettingsUpdateDialog.class, "HttpSettingsUpdateDialog.chkSyncOnStartup.text")); // NOI18N

        btnAuthenticate.setText(org.openide.util.NbBundle.getMessage(HttpSettingsUpdateDialog.class, "HttpSettingsUpdateDialog.btnAuthenticate.text")); // NOI18N
        btnAuthenticate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAuthenticateActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(btnAuthenticate)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(btnUpdate)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(btnCancel))
                    .add(layout.createSequentialGroup()
                        .add(17, 17, 17)
                        .add(jLabel1)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(15, 15, 15)
                                .add(chkSyncOnStartup)
                                .add(0, 183, Short.MAX_VALUE))
                            .add(layout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(txtURL)))))
                .add(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(8, 8, 8)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(txtURL, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(chkSyncOnStartup)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 42, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnUpdate)
                    .add(btnCancel)
                    .add(btnAuthenticate))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        try {
            model.setUrl(new URL(StringUtils.trim(txtURL.getText())));
            SingleModelManagers.HTTP_SETTINGS.save(model);

            HttpUpdateManager.create().updateSettings(true);

            NotificationUtils.info(String.format("Http Settings update from url '%s' was successful.", model.getUrl()));
            dispose();
        } catch (Exception e) {
            ErrorManager.getDefault().notify(e);
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnAuthenticateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAuthenticateActionPerformed
        HttpSettingsAuthenticationDialog dialog = new HttpSettingsAuthenticationDialog();

        if(StringUtils.isNotBlank(dialog.getUsername())) {
            dialog.setUsername(StringUtils.trim(dialog.getUsername()));
            dialog.setPassword(StringUtils.trim(dialog.getPassword()));
        }

        dialog.setVisible(true);

        if(!dialog.isCancelled()) {
            model.setName(dialog.getUsername());
            model.setPassword(dialog.getPassword());
        }
    }//GEN-LAST:event_btnAuthenticateActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAuthenticate;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JCheckBox chkSyncOnStartup;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtURL;
    // End of variables declaration//GEN-END:variables
}
