/*
 * Copyright 2012 adeleon.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ard.piraso.ui.api.views;

import ard.piraso.api.entry.Entry;
import ard.piraso.ui.api.manager.FontProviderManager;

import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import java.util.Collections;
import java.util.List;

/**
 *
 * @author adeleon
 */
public class NameValueTableTabView extends AbstractTabView<Entry> {

    private DefaultTableModel tableModel = new DefaultTableModel(0, 2) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false;
        }
    };

    private NameValueTableProvider provider;

    /**
     * Creates new form NameValueTabView
     */
    public NameValueTableTabView(Entry entry, NameValueTableProvider provider) {
        super(entry);

        this.provider = provider;
        initComponents();
        initTable();

        refreshView(entry);
    }

    private void initTable() {
        TableColumn nameColumn = jtable.getColumnModel().getColumn(0);
        TableColumn valueColumn = jtable.getColumnModel().getColumn(1);

        nameColumn.setHeaderValue("Name");
        nameColumn.setPreferredWidth(160);
        nameColumn.setMaxWidth(275);

        valueColumn.setHeaderValue("Value");
        valueColumn.setPreferredWidth(500);

        jtable.setShowHorizontalLines(false);
        jtable.setAutoscrolls(true);
        jtable.setColumnSelectionAllowed(false);
        jtable.getTableHeader().setReorderingAllowed(false);
    }
    
    @Override
    public void refreshView(Entry entry) {
        List<NameValue> nvs = provider.list(entry);

        if(btnAscending.isSelected()) {
            Collections.sort(nvs, NameValue.ASCENDING);
        } else if(btnDescending.isSelected()) {
            Collections.sort(nvs, NameValue.DESCENDING);
        }

        tableModel.setRowCount(0);
        for(NameValue nv : nvs) {
            tableModel.addRow(new Object[] {nv.getName(), nv.getValue()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jToolBar1 = new javax.swing.JToolBar();
        btnAscending = new javax.swing.JToggleButton();
        btnDescending = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtable = new javax.swing.JTable();

        setLayout(new java.awt.BorderLayout());

        jToolBar1.setBackground(new java.awt.Color(226, 226, 226));
        jToolBar1.setFloatable(false);
        jToolBar1.setOrientation(1);
        jToolBar1.setRollover(true);

        buttonGroup1.add(btnAscending);
        btnAscending.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ard/piraso/ui/api/icons/sort_ascend.png"))); // NOI18N
        btnAscending.setSelected(true);
        btnAscending.setText(org.openide.util.NbBundle.getMessage(NameValueTableTabView.class, "NameValueTableTabView.btnAscending.text")); // NOI18N
        btnAscending.setToolTipText(org.openide.util.NbBundle.getMessage(NameValueTableTabView.class, "NameValueTableTabView.btnAscending.toolTipText")); // NOI18N
        btnAscending.setFocusable(false);
        btnAscending.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAscending.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnAscending.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAscendingActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAscending);

        buttonGroup1.add(btnDescending);
        btnDescending.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ard/piraso/ui/api/icons/sort_descend.png"))); // NOI18N
        btnDescending.setText(org.openide.util.NbBundle.getMessage(NameValueTableTabView.class, "NameValueTableTabView.btnDescending.text")); // NOI18N
        btnDescending.setFocusable(false);
        btnDescending.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDescending.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btnDescending.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDescendingActionPerformed(evt);
            }
        });
        jToolBar1.add(btnDescending);

        add(jToolBar1, java.awt.BorderLayout.WEST);

        jtable.setFont(FontProviderManager.INSTANCE.getEditorDefaultFont());
        jtable.setModel(tableModel);
        jScrollPane1.setViewportView(jtable);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAscendingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAscendingActionPerformed
        refreshView(entry);
    }//GEN-LAST:event_btnAscendingActionPerformed

    private void btnDescendingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDescendingActionPerformed
        refreshView(entry);
    }//GEN-LAST:event_btnDescendingActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAscending;
    private javax.swing.JToggleButton btnDescending;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable jtable;
    // End of variables declaration//GEN-END:variables
}
