/*
 * Copyright (c) 2011. Piraso Alvin R. de Leon. All Rights Reserved.
 *
 * See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The Piraso licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package ard.piraso.ui.base.wizard;

import ard.piraso.ui.api.PreferenceProperty;
import ard.piraso.ui.api.PreferenceProvider;
import ard.piraso.ui.base.GeneralPreferenceProviderImpl;
import com.jgoodies.forms.layout.CellConstraints;
import com.jgoodies.forms.layout.FormLayout;
import org.apache.commons.collections.CollectionUtils;
import org.openide.util.Lookup;

import javax.swing.*;
import java.awt.*;
import java.util.*;
import java.util.List;

public final class NewMonitorWindowVisualPanel2 extends JPanel {

    private JCheckBox[] chkPreferences;
    private String[] preferenceKeys;
            
    /** Creates new form NewMonitorWindowVisualPanel2 */
    public NewMonitorWindowVisualPanel2() {
        initComponents();
        initPrefenceComponents();
    }
    
    private List<PreferenceProvider> getProviders() {
        Collection<? extends PreferenceProvider> providers = Lookup.getDefault().lookupAll(PreferenceProvider.class);
        List<PreferenceProvider> tmp = new ArrayList<PreferenceProvider>(providers);
        Collections.sort(tmp, new Comparator<PreferenceProvider>() {
            @Override
            public int compare(PreferenceProvider t, PreferenceProvider t1) {
                if(GeneralPreferenceProviderImpl.class.isInstance(t)) {
                    return -1;
                } else {
                    return 1;
                }
            }
        });      
        
        return tmp;
    }
    
    private void initPrefenceComponents() {
        Collection<? extends PreferenceProvider> providers = Lookup.getDefault().lookupAll(PreferenceProvider.class);
        CellConstraints c = new CellConstraints();
        
        int size = 0;
        for(PreferenceProvider provider : providers) {
            size += CollectionUtils.size(provider.getPreferences());
        }
                
        int l = 0, r = 2;
        chkPreferences = new JCheckBox[size];
        preferenceKeys = new String[size];
        Iterator<PreferenceProvider> itrpp = getProviders().iterator();
        for(int i = 0; i < providers.size(); i++) {
            PreferenceProvider provider = itrpp.next();

            JLabel lblHeader = new JLabel(provider.getName());
            Font of = lblHeader.getFont();
            lblHeader.setFont(new Font(of.getFamily(), Font.BOLD, of.getSize()));
            pnlPreferences.add(lblHeader, c.xyw(2, r, 3));
            r += 2;
            
            Iterator<? extends PreferenceProperty> itrp = provider.getPreferences().iterator();
            for(int j = 0; j < provider.getPreferences().size(); j++, l++) {
                PreferenceProperty prop = itrp.next();
                
                preferenceKeys[l] = prop.getName();
                chkPreferences[l] = new JCheckBox();
                chkPreferences[l].setText(provider.getMessage(prop.getName()));
                chkPreferences[l].setSelected(prop.isDefaultValue());

                pnlPreferences.add(chkPreferences[l], c.xy(4, r));                
                r += 2;
            }
        }
    }
    
    private FormLayout createLayout() {
        StringBuilder buf = new StringBuilder();
                
        buf.append("2dlu, ");
        
        for(PreferenceProvider provider : getProviders()) {            
            buf.append("p, 4dlu, ");
            
            Iterator<? extends PreferenceProperty> itrp = provider.getPreferences().iterator();
            while(itrp.hasNext()) {
                PreferenceProperty prop = itrp.next();
                
                buf.append("p, ");
                buf.append(itrp.hasNext() ? " 2dlu, " : " 6dlu, ");
            }
        }
        
        buf.append("2dlu");
        
        return new FormLayout("2dlu, 6dlu, 2dlu, p:g, 2dlu", buf.toString());
    }
    
    @Override
    public String getName() {
        return "Monitoring Preferences";
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        pnlPreferences = new javax.swing.JPanel();

        pnlPreferences.setOpaque(false);
        pnlPreferences.setLayout(createLayout());
        jScrollPane1.setViewportView(pnlPreferences);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlPreferences;
    // End of variables declaration//GEN-END:variables

}
