/*
 * Copyright 2012 adeleon.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ard.piraso.ui.base;

import org.netbeans.api.settings.ConvertAsProperties;
import org.openide.awt.ActionID;
import org.openide.awt.ActionReference;
import org.openide.util.NbBundle.Messages;
import org.openide.windows.TopComponent;

import javax.swing.*;
import javax.swing.tree.DefaultMutableTreeNode;

/**
 * Top component which displays something.
 */
@ConvertAsProperties(dtd = "-//ard.piraso.ui.base//RequestTree//EN", autostore = false)
@TopComponent.Description(preferredID = "RequestTreeTopComponent", persistenceType = TopComponent.PERSISTENCE_ALWAYS)
@TopComponent.Registration(mode = "leftSlidingSide", openAtStartup = true)
@ActionID(category = "Window", id = "ard.piraso.ui.base.RequestTreeTopComponent")
@ActionReference(path = "Menu/Window")
@TopComponent.OpenActionRegistration(displayName = "#CTL_RequestTreeAction",
preferredID = "RequestTreeTopComponent")
@Messages({
    "CTL_RequestTreeAction=RequestTree",
    "CTL_RequestTreeTopComponent=RequestTree Window",
    "HINT_RequestTreeTopComponent=This is a RequestTree window"
})
public final class RequestTreeTopComponent extends TopComponent {
    
    private DefaultMutableTreeNode root;

    public RequestTreeTopComponent() {
        initComponents();
        setName(Bundle.CTL_RequestTreeTopComponent());
        setToolTipText(Bundle.HINT_RequestTreeTopComponent());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTree = new JTree(root);

        setLayout(new java.awt.BorderLayout());

        jTree.setRootVisible(false);
        jScrollPane1.setViewportView(jTree);

        add(jScrollPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTree;
    // End of variables declaration//GEN-END:variables

    @Override
    public void componentOpened() {
    }

    @Override
    public void componentClosed() {
    }

    void writeProperties(java.util.Properties p) {
        p.setProperty("version", "1.0");
    }

    void readProperties(java.util.Properties p) {
        String version = p.getProperty("version");
    }
}
