/*
 * Copyright 2012 adeleon.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package ard.piraso.ui.base;

import ard.piraso.ui.api.SVNSyncModel;
import ard.piraso.ui.api.extension.AbstractDialog;
import ard.piraso.ui.api.manager.SingleModelManagers;

/**
 *
 * @author adeleon
 */
public class SVNSyncDialog extends AbstractDialog {

    private SVNSyncModel model;

    /**
     * Creates new form SVNSyncDialog
     */
    public SVNSyncDialog() {
        super();
        setTitle("SVN Synchronize settings");
        initComponents();
        
        getRootPane().setDefaultButton(btnSync);

        model = SingleModelManagers.SYNC_SETTINGS.get();

        if(model.getUrl() != null) {
            txtURL.setText(model.getUrl().toString());
        }

        chkSyncOnStartup.setSelected(model.isLoadOnStartup());
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtURL = new javax.swing.JTextField();
        btnSync = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        chkSyncOnStartup = new javax.swing.JCheckBox();
        btnAuthenticate = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText(org.openide.util.NbBundle.getMessage(SVNSyncDialog.class, "SVNSyncDialog.jLabel1.text")); // NOI18N

        txtURL.setText(org.openide.util.NbBundle.getMessage(SVNSyncDialog.class, "SVNSyncDialog.txtURL.text")); // NOI18N

        btnSync.setText(org.openide.util.NbBundle.getMessage(SVNSyncDialog.class, "SVNSyncDialog.btnSync.text")); // NOI18N
        btnSync.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSyncActionPerformed(evt);
            }
        });

        jButton2.setText(org.openide.util.NbBundle.getMessage(SVNSyncDialog.class, "SVNSyncDialog.jButton2.text")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        chkSyncOnStartup.setSelected(true);
        chkSyncOnStartup.setText(org.openide.util.NbBundle.getMessage(SVNSyncDialog.class, "SVNSyncDialog.chkSyncOnStartup.text")); // NOI18N

        btnAuthenticate.setText(org.openide.util.NbBundle.getMessage(SVNSyncDialog.class, "SVNSyncDialog.btnAuthenticate.text")); // NOI18N
        btnAuthenticate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAuthenticateActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(btnAuthenticate)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(btnSync)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(jButton2))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                        .add(17, 17, 17)
                        .add(jLabel1)
                        .add(15, 15, 15)
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(layout.createSequentialGroup()
                                .add(chkSyncOnStartup)
                                .add(0, 128, Short.MAX_VALUE))
                            .add(txtURL))))
                .add(14, 14, 14))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(8, 8, 8)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel1)
                    .add(txtURL, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(chkSyncOnStartup)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 42, Short.MAX_VALUE)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnSync)
                    .add(jButton2)
                    .add(btnAuthenticate))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnSyncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSyncActionPerformed
        SingleModelManagers.SYNC_SETTINGS.save(model);


    }//GEN-LAST:event_btnSyncActionPerformed

    private void btnAuthenticateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAuthenticateActionPerformed

    }//GEN-LAST:event_btnAuthenticateActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btnAuthenticate;
    private javax.swing.JButton btnSync;
    private javax.swing.JCheckBox chkSyncOnStartup;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField txtURL;
    // End of variables declaration//GEN-END:variables
}
